### ISSUE TITLE
Feature: pass attributes to Web component with binding

### ISSUE THREAD

**Issue by codingnuclei** [angular-extensions/elements#24]
PROBLEM

Currently I believe that you can not set webcomponents attributes/properties via angular data binding.

SOLUTION

It would be nice if the directive acts as a wrapper, giving support for properties to be passed to the webcomponent.

PROPOSED TECHINCAL SOLUTION

Add another input to the directives for data to pass to the webcomponent `@Input(axLazyElementsDataBinding) dataBinding`

using ngOnUpdate detect updates.

Using the angular renderer2 service set the webcomponent's attribute with the updated data

Do you think this would be in scope of this library?

**Comment by tomastrajan** [comment]
Hi @codingnuclei !

Intersting idea but in my opinion this is but out of scope of what this library does. I get what you want to achieve, but that's more on the web component / element implementation side and this lib is focused on the consumer of the webcomponents / elements instead.

So basically, this is not a problem when using Angular elements because they create such a wrapper for you. Plain web components have to implement such behavior manually, listening to attribute changes, potentially parsing complex objects from strings...

**Comment by codingnuclei** [comment]
@tomastrajan

Agreed. 👍😊

Might be nice as directive in its own right. 

Thanks

**Comment by tomastrajan** [comment]
@codingnuclei its basically what `import { createCustomElement } from '@angular/elements';` does for Angular components and you would want such a helper but for vanilla web components ;)
