### ISSUE TITLE
Hot working on stackblitz

### ISSUE THREAD

**Issue by BossOz** [angular-extensions/elements#43]
Hello @tomastrajan,

I'm trying to test angular-extensions on stackblitz but my project is not working.
[https://stackblitz.com/edit/angular-extensions-elements](https://stackblitz.com/edit/angular-extensions-elements)

What I'm missing?
Thank you!

**Comment by tomastrajan** [comment]
Hi @BossOz !

I was trying it a while ago and unfortunately, StackBlitz is doing some interceptions of all requests with web workers which breaks some url stuff. It caused by their infrastructure which actually makes all that amazing magic possible.

So currently it is not possible to run this on stackblitz :/

**Comment by BossOz** [comment]
Ok! Thank you!
