### ISSUE TITLE
Support for load Angular Elements in a Angular Elements

### ISSUE THREAD

**Issue by ye3i** [angular-extensions/elements#9]
Hi, brilliant job!

Correct me if I am wrong but I think there is a case the library is not covering.
If we are in one of a micro-apps (angular-elements) loaded in shell app, and we want to load other angular elements dynamically, for example widget shared beetwen micro-apps.
When we import LazyElementsModule in Angular Elements, a new instance of LazyElementsLoaderService will be created without knowledge of already registered items. 

It would be great if your library covered such a case.

**Comment by tomastrajan** [comment]
@ye3i thanks for feedback! Yes as you said the current solution keeps elements and parent totally isolated so the service is not shared, it could be possible to add optional option to enable sharing which could be facilitated through some secret property stored on window or something, will definitively have a look!

**Comment by angelfraga** [comment]
@ye3i good question 👍
In my opinion, I am not 100% if this feature should be tackled in this library itself, but somehow it is a topic has to be raised and solved in the angular micro-apps world.

There are different approaches to shared it e.g making the service instance global var as @tomastrajan mentioned.
But since angular itself(at least until version 8.x)  doesn't provide an official way for sharing it, it definitively depends on each implementation. 

After considering a few approaches, in my opinion a good idea will be to add the ability to consume this state from localStorage/cache instead of the service private state. Then use the injection token mechanism for giving a common key for consuming the same state. 

```typescript
export const LOCAL_STORAGE_KEY_FOR_WEB_ELEMENTS_STATE= new InjectionToken<string>('LocalStorageKeyForWebElementsState');
```

Then in `micro-app-one.module.ts` :

```typescript
@NgModue({
  providers: [
    { provide: LOCAL_STORAGE_KEY_FOR_WEB_ELEMENTS_STATE, useValue: 'myKey' }
  ]
})
export class MicroAppOneModule { }
```
Then in `micro-app-two.module.ts` :

```typescript
@NgModue({
  providers: [
    { provide: LOCAL_STORAGE_KEY_FOR_WEB_ELEMENTS_STATE, useValue: 'myKey' }
  ]
})
export class MicroAppTwoModule { }
```

**Comment by angelfraga** [comment]
@tomastrajan 
One question,  is the state goal just decide if we have to load the bundle of the web element?

Then most probably we don't have to use this state at all. 

```
if(document.createElement(name).constructor !== HTMLElement) {
  // load the script from the url 
}
```

I am wrong?

**Comment by tomastrajan** [comment]
@angelfraga do I understand correctly that you mean we don't have to keep registry of loaded elements because we can just check `document.createElement(name).constructor === HTMLElement` ?

If so then this will not work if we had multiple same elements in the same template, they will trigger concurrent requests. Currently once first element triggers bundle download, every other gets a promise... Maybe we could somehow combine the two? SO that we still use service but before that we try to check document so that we may prevent at least some duplicate bundle downloads across multiple elements using elements ?

**Comment by angelfraga** [comment]
I didn't note it when wrote the last comment. You are totally right. The only way for preventing duplicate bundle downloads is having the state.


Then I would vote for providing a base service for handling the state, afterward, each implementation can use the default state service (the current mechanism) or another like the local storage I proposed above.
